// Compose and check a canonical review or QA verdict comment (ENGINEERING_SYSTEM §6).
// Pure functions; verdict.mjs does the reads and prints the body; it never posts.
import { canonicalBlock, field } from "../engineering/metadata-parser.mjs";

const SHA_RE = /^[0-9a-f]{40}$/;
const AGENT_RE = /^(claude|codex|chatgpt|grok):[A-Za-z0-9_-]+:(reviewer|qa)$/;
const VERDICTS = new Set(["PASS", "FAIL", "BLOCK"]);
export const FOOTER = "---\n_Generated by [Claude Code](https://claude.ai/code)_";

const USAGE =
  "usage: verdict <pr> --agent <runtime:slot:reviewer|qa> --head <reviewed sha> --verdict PASS|FAIL|BLOCK\n" +
  "       [--report <file>] [--qa-scope <text>] [--model <name>] [--fallback <slug — reason>]";

const oneLine = (v) => typeof v === "string" && v.trim() !== "" && !/[\r\n]/.test(v);

/** argv -> options, or {error}. Every value flag takes exactly one value. */
export function parseVerdictArgs(args) {
  const o = {};
  const flags = { "--agent": "agent", "--head": "head", "--verdict": "verdict", "--report": "report",
    "--qa-scope": "qaScope", "--model": "model", "--fallback": "fallback" };
  const rest = [];
  for (let i = 0; i < args.length; i += 1) {
    const a = args[i];
    if (flags[a]) {
      const v = args[i + 1];
      if (v === undefined || v.startsWith("--")) return { error: `${a} needs a value\n${USAGE}` };
      o[flags[a]] = v;
      i += 1;
    } else if (a.startsWith("--")) return { error: `unknown flag ${a}\n${USAGE}` };
    else rest.push(a);
  }
  if (rest.length !== 1 || !/^[1-9]\d*$/.test(rest[0])) return { error: USAGE };
  o.pr = Number(rest[0]);
  if (!AGENT_RE.test(o.agent ?? "")) return { error: `--agent must be <runtime>:<slot>:reviewer|qa\n${USAGE}` };
  o.role = o.agent.endsWith(":qa") ? "qa" : "reviewer";
  if (!SHA_RE.test(o.head ?? "")) return { error: "--head must be the full 40-character reviewed SHA (lowercase)" };
  o.verdict = String(o.verdict ?? "").toUpperCase();
  if (!VERDICTS.has(o.verdict)) return { error: "--verdict must be PASS, FAIL or BLOCK" };
  if (o.role === "qa" && !oneLine(o.qaScope)) return { error: "QA verdict needs a one-line --qa-scope" };
  if (o.role === "reviewer" && o.qaScope !== undefined) return { error: "--qa-scope is for QA verdicts only" };
  for (const k of ["model", "fallback"]) {
    if (o[k] !== undefined && !oneLine(o[k])) return { error: `--${k} must be one line` };
  }
  if (o.fallback !== undefined && o.role !== "qa") return { error: "--fallback is for QA verdicts only" };
  return o;
}

/**
 * Report checks. A reviewer report ends with the totals line the review skill
 * prescribes; a PASS with a KRITIČNO or VAŽNO finding is refused, as is a
 * report line that would start a second metadata block.
 */
export function checkReport(report, { role, verdict }) {
  const text = String(report ?? "").trim();
  if (!text) return null;
  if (/^(agent-review|review-head|review-verdict|qa-agent|qa-head|qa-verdict|qa-scope|owner-override|override-head):/im.test(text)) {
    return "report must not contain verdict or override metadata lines";
  }
  if (role === "reviewer") {
    const totals = text.match(/^Ukupno:\s*(\d+)\s*kritičn\w*,\s*(\d+)\s*važn\w*,\s*(\d+)\s*manj\w*\.?\s*$/im);
    if (!totals && !/^Bez nalaza\.?\s*$/im.test(text)) {
      return "report must end with 'Ukupno: N kritično, N važno, N manje.' or 'Bez nalaza.'";
    }
    if (verdict === "PASS" && totals && (Number(totals[1]) > 0 || Number(totals[2]) > 0)) {
      return "PASS with open KRITIČNO or VAŽNO findings; resolve them or use FAIL";
    }
  }
  return null;
}

/** One comment: the canonical block first, then the report, then the footer. */
export function composeVerdict({ role, agent, head, verdict, qaScope, model, fallback, report }) {
  const lines = role === "qa"
    ? [`QA-Agent: ${agent}`, `QA-Head: ${head}`, `QA-Verdict: ${verdict}`, `QA-Scope: ${qaScope}`]
    : [`Agent-Review: ${agent}`, `Review-Head: ${head}`, `Review-Verdict: ${verdict}`];
  if (model) lines.push(`${role === "qa" ? "QA" : "Review"}-Model: ${model}`);
  if (fallback) lines.push(`Provider-Fallback: ${fallback}`);
  const parts = [lines.join("\n")];
  const text = String(report ?? "").trim();
  if (text) parts.push(text);
  if (agent.startsWith("claude:")) parts.push(FOOTER);
  return `${parts.join("\n\n")}\n`;
}

/** Read the composed body back the way the gate does; null when it parses as intended. */
export function verifyComposed(body, { role, agent, head, verdict }) {
  const [a, h, v] = role === "qa" ? ["QA-Agent", "QA-Head", "QA-Verdict"] : ["Agent-Review", "Review-Head", "Review-Verdict"];
  if (!canonicalBlock(body, a)) return `first line is not ${a}:`;
  if (field(body, a) !== agent || field(body, h) !== head || field(body, v)?.toUpperCase() !== verdict) {
    return "composed block does not read back as the given agent, head and verdict";
  }
  return null;
}

/** The PR head as GitHub reports it and as the branch ref says must both be the reviewed head. */
export function headProblem({ reviewed, prHead, refHead, state }) {
  if (state !== "open") return `PR is ${state}`;
  if (!prHead || prHead !== refHead) return `PR head ${prHead ?? "?"} and branch ref ${refHead ?? "?"} differ; a push is in flight, read again`;
  if (prHead !== reviewed) return `current head ${prHead} is not the reviewed head ${reviewed}; review the new head`;
  return null;
}
